// This file was automatically generated from template.soy.
// Please don't edit this file by hand.

if (typeof cakepage == 'undefined') { var cakepage = {}; }


cakepage.header = function(opt_data, opt_ignored) {
  return '<nav class="navbar navbar-default" role="navigation"><!-- Brand and toggle get grouped for better mobile display --><div class="navbar-header"><button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button><a class="navbar-brand" href="#">Cake</a></div><!-- Collect the nav links, forms, and other content for toggling --><div class="collapse navbar-collapse navbar-ex1-collapse"><ul class="nav navbar-nav"><li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">About<b class="caret"></b></a><ul class="dropdown-menu"><li><a href="#">About Cake</a></li><li><a href="#">Developer</a></li><li><a href="#">add contents</a></li></ul></li><li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Project<b class="caret"></b></a><ul class="dropdown-menu"><li><a href="project/prjIndex.html">New Project</a></li><li><a href="#">Open Project</a></li><li><a href="#">add contents</a></li></ul></li><li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Etc<b class="caret"></b></a><ul class="dropdown-menu"><li><a href="#">Donation</a></li><li><a href="#">Help</a></li><li><a href="#">add contents</a></li></ul></li></ul><ul class="nav navbar-nav navbar-right"><button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#loginModal">LogIn</button><!-- Modal --><div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button><h4 class="modal-title">LogIn</h4></div><div class="modal-body"><form role="form"><div class="form-group form-horizontal"><label for="md_lb_Email1" class="col-lg-2 control-label">Email</label><input type="email" class="form-control" id="inputEmail1" placeholder="Email"></div><div class="form-group form-horizontal"><label for="md_lb_Password1" class="col-lg-2 control-label">Password</label><input type="password" class="form-control" id="inputPassword1" placeholder="Password"></div><div class="form-group"><div class="checkbox"><label><input type="checkbox">Remember me</label></div></div><div class="form-group"><!--' + cakepage.signup(null) + ' Sign up--><a href="signup.html">Sign up</a></div></form></div><div class="modal-footer"><button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button><button type="button" class="btn btn-primary">LogIn</button></div></div><!-- /.modal-content --></div><!-- /.modal-dialog --></div><!-- /.modal --></ul></div><!-- /.navbar-collapse --></nav>';
};


cakepage.signup = function(opt_data, opt_ignored) {
  return '<div class="container"><form class="form-signin" role="form"><h2 class="form-signin-heading">Please sign up :^)</h2><input type="email" class="form-control" placeholder="Email address" required="" autofocus=""><input type="text" class="form-control" placeholder="Name" required="" autofocus=""><input type="password" class="form-control" placeholder="Password" required=""><button class="btn btn-lg btn-primary btn-block" type="submit">Sign up</button></form></div>';
};


cakepage.secondHeader = function(opt_data, opt_ignored) {
  return '<nav class="navbar navbar-default" role="navigation"><!-- Brand and toggle get grouped for better mobile display --><div class="navbar-header"><button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span></button></div><!-- Collect the nav links, forms, and other content for toggling --><div class="collapse navbar-collapse navbar-ex1-collapse"><ul class="nav navbar-nav"><li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">File<b class="caret"></b></a><ul class="dropdown-menu"><li><a href="#">Save As</a></li><li><a href="#">Download</a></li><li><a href="#">Rename</a></li></ul></li><li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Tool<b class="caret"></b></a><ul class="dropdown-menu"><li><a href="#">Tool1</a></li><li><a href="#">Tool2</a></li><li><a href="#">Tool3</a></li></ul></li></div><!-- /.navbar-collapse --></nav>';
};


cakepage.blockpageView = function(opt_data, opt_ignored) {
  return '<nav class="navbar navbar-default" role="navigation"><div><ul class="nav nav-pills nav-stacked"><li class="active"><a href="#">Pre</a></li><li><a href="#">Main</a></li><li><a href="#">sub</a></li></ul></div></nav><div><label> blockkk.. </label></div>';
};
