// This file was automatically generated from template.soy.
// Please don't edit this file by hand.

if (typeof cakepage == 'undefined') { var cakepage = {}; }


cakepage.header = function(opt_data, opt_ignored) {
  return '<div class="header"><nav class="navbar navbar-default" role="navigation" style="background-color: #ffffff; margin-bottom: 5px;"><!-- Brand and toggle get grouped for better mobile display --><div class="navbar-header"><button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button><a class="navbar-brand" href="index.html">Cake</a></div><!-- Collect the nav links, forms, and other content for toggling --><div class="collapse navbar-collapse navbar-ex1-collapse"><ul class="nav navbar-nav"><li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">About<b class="caret"></b></a><ul class="dropdown-menu"><li><a href="#">About Cake</a></li><li><a href="#">Developer</a></li><li><a href="#">add contents</a></li></ul></li><li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Project<b class="caret"></b></a><ul class="dropdown-menu"><li><a href="prjIndex.html">New Project</a></li><li><a href="#">Open Project</a></li><li><a href="#">add contents</a></li></ul></li><li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Etc<b class="caret"></b></a><ul class="dropdown-menu"><li><a href="#">Donation</a></li><li><a href="#">Help</a></li><li><a href="#">add contents</a></li></ul></li></ul><ul class="nav navbar-right"><!-- Modal --><div id="loginModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">x</span><span class="sr-only">Close</span></button><h4 class="modal-title">LogIn</h4></div><div class="modal-body" style="padding-left: 40px; padding-right: 40px;"><form role="form"><div class="form-group"><input type="email" class="form-control" id="inputEmail1" placeholder="Email" required="" autofocus=""><input type="password" class="form-control" id="inputPassword1" placeholder="Password" required=""></div><div class="form-group" style="TEXT-ALIGN:center"><div class="checkbox"><label><input type="checkbox">Remember me</label></div></div><div class="form-group" style="TEXT-ALIGN:center"><!--' + cakepage.signup(null) + ' Sign up--><a href="signup.html">Sign up</a></div></form></div><div class="modal-footer"><button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button><button type="button" class="btn btn-primary">LogIn</button></div></div><!-- /.modal-content --></div><!-- /.modal-dialog --></div><!-- /.modal --><button class="btn btn-primary" data-toggle="modal" data-target="#loginModal" style="margin-top: 8px;">LogIn</button></ul></div><!-- /.navbar-collapse --></nav></div>';
};


cakepage.signup = function(opt_data, opt_ignored) {
  return '<div><form class="form-signin" role="form" style="max-width: 330px; padding: 15px; margin: 0 auto;"><h2 class="form-signin-heading">Please sign up :^)</h2><input type="email" class="form-control" placeholder="Email address" required="" autofocus=""><input type="text" class="form-control" placeholder="Name" required=""><input type="password" class="form-control" placeholder="Password" required=""><div style="padding-bottom: 10px"></div><button class="btn btn-lg btn-primary btn-block" type="submit">Sign up</button></form></div>';
};


cakepage.secondHeader = function(opt_data, opt_ignored) {
  return '<nav class="navbar navbar-default" role="navigation" style="background-color: #ffffff; margin-bottom: 5px;"><!-- Brand and toggle get grouped for better mobile display --><div class="navbar-header"><button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span></button></div><!-- Collect the nav links, forms, and other content for toggling --><div class="collapse navbar-collapse navbar-ex1-collapse"><ul class="nav navbar-nav"><li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">File<b class="caret"></b></a><ul class="dropdown-menu"><li><a href="#">Save As</a></li><li><a href="#">Download</a></li><li><a href="#">Rename</a></li></ul></li><li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Tool<b class="caret"></b></a><ul class="dropdown-menu"><li><a href="#">Tool1</a></li><li><a href="#">Tool2</a></li><li><a href="#">Tool3</a></li></ul></li></div><!-- /.navbar-collapse --></nav>';
};


cakepage.blockpageView = function(opt_data, opt_ignored) {
  return '<div><div class="col-xs-12 col-sm-3 col-md-2"><div style="padding-top: 10px; padding-bottom: 10px; border-radius: 4px;"><div style="background-color: #FFFFFF; border: 1px solid #e7e7e7; border-radius: 5px;"><ul class="nav nav-pills nav-stacked"><li class="active"><a href="#">Pre</a></li><li><a href="#">Main</a></li><accordion><div class="panel panel-default ng-isolate-scope" heading="Functions" is-open="true" style="margin: 1px"><div class="panel-heading"><h4 class="panel-title"><a class="accordion-toggle ng-binding" ng-click="isOpen = !isOpen" accordion-transclude="heading">sub functions</a></h4></div><div class="panel-collapse collapse in" collapse="!isOpen" style="height: auto"><div class="panel-body" ng-transclude><div class="list-group ng-scope" adjustheight="325"><a class="list-group-item">sub1</a><a class="list-group-item">sub2</a><!-- ngRepeat: k in pages.keys().sort() --><!-- end ngRepeat: k in pages.keys().sort() --><!-- end ngRepeat: k in pages.keys().sort() --></div><center><div class="btn-group btn-group-sm ng-scope"><button type="button" class="btn btn-default" ng-click="newPage()"><span class="glyphicon glyphicon-plus"></span></button><button type="button" class="btn btn-default" ng-click="deletePage(currentPageName)"><span class="glyphicon glyphicon-minus"></span></button></div></center></div></div></div></accordion></ul></div></div></div><div class="col-xs-12 col-sm-6 col-md-10"><label> blockkk.. </label></div></div>';
};
